import { linkClaimEvidence, recordClaim } from "../evidence/claim-store.js";
import { isOwnerCapability } from "../authority/capability-broker.js";
import { getCorpusSnapshot, getSearchEvent, listCorpusSnapshots, runAuthorizedRetrieval } from "./retrieval-store.js";
import { getCorpusRecord, getQueryVersion } from "./literature-store.js";
import { transaction } from "../persistence/schema.js";
import { isoNow, newId } from "../persistence/storage-utils.js";
import { assertWritable, type ProjectHandle } from "../project/project-store.js";
import { ProjectStoreError } from "../project/project-types.js";
import type { ContributionProposal, ContributionProposalRequest, CounterSearchRequest, CounterSearchResult, CorpusRecord, GapAssessment, GapAssessmentRequest, GapInspection, LiteratureRetrievalAdapter, RetrievalHit } from "./literature-types.js";
import { allowed, assertLiteratureSchema, beginOperation, completeOperation, json, operation, parse, payloadHash, recordId, requireCapability, requireCommand, requireText, text } from "./literature-utils.js";

const FORBIDDEN_STATUSES = new Set(["universally-novel", "exhaustive-absence", "proven-gap", "no-contrary-evidence-exists"]);
function gapRow(row: Record<string, unknown>): GapAssessment { return { id: text(row, "id"), snapshotId: text(row, "snapshot_id"), queryVersionIds: parse(row.query_version_ids, []), searchedAt: text(row, "searched_at"), proposition: text(row, "proposition"), status: text(row, "status") as GapAssessment["status"], qualifications: parse(row.qualifications, []), origin: text(row, "origin") as GapAssessment["origin"], createdAt: text(row, "created_at") }; }
function contributionRow(row: Record<string, unknown>): ContributionProposal { return { id: text(row, "id"), gapId: text(row, "gap_id"), proposition: text(row, "proposition"), qualifications: parse(row.qualifications, []), origin: text(row, "origin") as ContributionProposal["origin"], createdAt: text(row, "created_at") }; }
function row(handle: ProjectHandle, table: string, id: string): Record<string, unknown> { const found = handle.db.prepare(`SELECT * FROM ${table} WHERE id = ?`).get(id) as Record<string, unknown> | undefined; if (!found) {throw new ProjectStoreError("literature-not-found", `${table} record was not found`);} return found; }
function originFor(handle: ProjectHandle, capability: unknown, requested?: GapAssessment["origin"]): GapAssessment["origin"] { const owner = isOwnerCapability(capability) && capability.ownerId === handle.project.ownerId; if (requested === "owner-recorded" && !owner) {throw new ProjectStoreError("forbidden", "only the owner may record owner-origin gap data");} return owner ? (requested ?? "owner-recorded") : "specialist-proposed"; }
function queryIdsBelong(handle: ProjectHandle, capability: unknown, ids: readonly string[], protocolId: string): void { if (ids.length === 0) {throw new ProjectStoreError("invalid-gap", "gap assessment requires query versions");} for (const id of ids) {if (getQueryVersion(handle, capability, id).protocolVersionId !== protocolId) {throw new ProjectStoreError("invalid-gap", "query version is outside the gap protocol scope");}} }

export function recordGapAssessment(handle: ProjectHandle, capability: unknown, request: GapAssessmentRequest): GapAssessment {
  assertWritable(handle); assertLiteratureSchema(handle); requireCapability(handle, capability, ["literature:assess-gap"], "gap assessment requires literature:assess-gap capability"); const commandId = requireCommand(request.commandId); const snapshot = getCorpusSnapshot(handle, capability, request.snapshotId); const event = getSearchEvent(handle, capability, snapshot.searchEventId); queryIdsBelong(handle, capability, request.queryVersionIds, event.protocolVersionId); const proposition = requireText(request.proposition, "proposition"); const status = request.status ?? "proposed"; if (FORBIDDEN_STATUSES.has(status)) {throw new ProjectStoreError("invalid-gap-status", "universal novelty and exhaustive absence statuses are not permitted");} const searchedAt = request.searchedAt ?? event.searchedAt; if (searchedAt !== event.searchedAt) {throw new ProjectStoreError("invalid-gap", "searchedAt must match the named search event");} const origin = originFor(handle, capability, request.origin); const payload = { snapshotId: request.snapshotId, queryVersionIds: request.queryVersionIds, searchedAt, proposition, status, qualifications: request.qualifications ?? [], origin }; const existing = beginOperation(handle, commandId, payloadHash(payload)); if (existing?.status === "complete") {return gapRow(row(handle, "gap_assessments", existing.resultId!));} const id = recordId("gap"); const createdAt = isoNow(); transaction(handle.db, () => handle.db.prepare("INSERT INTO gap_assessments (id, snapshot_id, query_version_ids, searched_at, proposition, status, qualifications, origin, command_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id, request.snapshotId, json(request.queryVersionIds), searchedAt, proposition, status, json(request.qualifications ?? []), origin, commandId, createdAt)); completeOperation(handle, commandId, id, "gap-assessment"); return gapRow(row(handle, "gap_assessments", id));
}
export function getGapAssessment(handle: ProjectHandle, capability: unknown, id: string): GapAssessment { assertLiteratureSchema(handle); if (!allowed(handle, capability, ["literature:inspect"]) && !allowed(handle, capability, ["literature:assess-gap"])) {throw new ProjectStoreError("forbidden", "gap inspection requires a literature capability");} return gapRow(row(handle, "gap_assessments", id)); }
export function listGapAssessments(handle: ProjectHandle, capability: unknown): readonly GapAssessment[] { assertLiteratureSchema(handle); requireCapability(handle, capability, ["literature:inspect"], "gap inspection requires literature:inspect capability"); return (handle.db.prepare("SELECT * FROM gap_assessments ORDER BY created_at, id").all() as Array<Record<string, unknown>>).map(gapRow); }
export function recordContributionProposal(handle: ProjectHandle, capability: unknown, request: ContributionProposalRequest): ContributionProposal { assertWritable(handle); assertLiteratureSchema(handle); requireCapability(handle, capability, ["literature:assess-gap"], "contribution recording requires literature:assess-gap capability"); const commandId = requireCommand(request.commandId); row(handle, "gap_assessments", request.gapId); const proposition = requireText(request.proposition, "proposition"); if (request.qualifications.length === 0) {throw new ProjectStoreError("invalid-contribution", "qualified contribution proposals require qualifications");} if (/\b(universal(?:ly)?|exhaustive|no contrary evidence)\b/i.test(proposition)) {throw new ProjectStoreError("invalid-contribution", "contribution proposals cannot claim universal novelty or exhaustive absence");} const origin = originFor(handle, capability, request.origin); const payload = { gapId: request.gapId, proposition, qualifications: request.qualifications, origin }; const existing = beginOperation(handle, commandId, payloadHash(payload)); if (existing?.status === "complete") {return contributionRow(row(handle, "contribution_proposals", existing.resultId!));} const id = recordId("contribution"); const createdAt = isoNow(); transaction(handle.db, () => handle.db.prepare("INSERT INTO contribution_proposals (id, gap_id, proposition, qualifications, origin, command_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)").run(id, request.gapId, proposition, json(request.qualifications), origin, commandId, createdAt)); completeOperation(handle, commandId, id, "contribution-proposal"); return contributionRow(row(handle, "contribution_proposals", id)); }
export function getContributionProposal(handle: ProjectHandle, capability: unknown, id: string): ContributionProposal { assertLiteratureSchema(handle); requireCapability(handle, capability, ["literature:inspect"], "contribution inspection requires literature:inspect capability"); return contributionRow(row(handle, "contribution_proposals", id)); }

export async function runCounterSearch(handle: ProjectHandle, capability: unknown, request: CounterSearchRequest): Promise<CounterSearchResult> {
  assertWritable(handle); assertLiteratureSchema(handle); requireCapability(handle, capability, ["literature:assess-gap", "claim:record", "evidence:inspect"], "counter-search requires gap assessment and E07 challenging-evidence capabilities"); const gap = getGapAssessment(handle, capability, request.gapId); const baseSnapshot = getCorpusSnapshot(handle, capability, gap.snapshotId); const baseEvent = getSearchEvent(handle, capability, baseSnapshot.searchEventId); const query = getQueryVersion(handle, capability, request.queryVersionId); if (!gap.queryVersionIds.includes(query.id) || query.protocolVersionId !== baseEvent.protocolVersionId) {throw new ProjectStoreError("invalid-gap", "counter-search query is outside the gap protocol scope");} const commandId = requireCommand(request.commandId); const payload = { gapId: request.gapId, queryVersionId: request.queryVersionId, searchedAt: request.searchedAt, contraryHits: request.contraryHits ?? [] }; const existing = beginOperation(handle, commandId, payloadHash(payload)); if (existing?.status === "complete") { const saved = row(handle, "counter_searches", existing.resultId!); const event = getSearchEvent(handle, capability, text(saved, "search_event_id")); const snapshot = getCorpusSnapshot(handle, capability, event.id); return { id: text(saved, "id"), gap, searchEvent: event, snapshot, contraryCorpusRecordIds: parse(saved.contrary_record_ids, []), challengingEvidenceItemIds: parse(saved.challenging_evidence_item_ids, []) }; }
  const adapter: LiteratureRetrievalAdapter = request.adapter ?? { retrieve: () => ({ hits: request.contraryHits ?? [], coverageLimits: [{ kind: "counter-search", reason: "targeted counter-search scope", queryVersionId: query.id }] }) };
  const event = await runAuthorizedRetrieval(handle, capability, { commandId: `${commandId}:search`, queryVersionId: query.id, adapter, searchedAt: request.searchedAt }); const snapshots = listCorpusSnapshotsInternal(handle, event.id); const snapshot = snapshots[0]; if (!snapshot) {throw new ProjectStoreError("literature-operation-incomplete", "counter-search did not produce a snapshot");} const contraryIds = snapshot.corpusRecordIds; const challenging: string[] = [];
  for (const recordId of contraryIds) {
    const record = getCorpusRecord(handle, capability, recordId); const itemId = (request.contraryHits ?? []).find((hit) => hit.corpusRecordId === recordId)?.evidenceItemId ?? evidenceItemForSource(handle, record.sourceVersionId);
    if (!itemId) {throw new ProjectStoreError("counter-search-incomplete", "every contrary record requires located E07 evidence for a challenging link");}
    const claim = recordClaim(handle, capability, { commandId: `${commandId}:claim:${recordId}`, statement: gap.proposition, scope: { gapId: gap.id, searchEventId: event.id }, qualification: "challenged by a retained scoped counter-search record", origin: "specialist-proposed" });
    linkClaimEvidence(handle, capability, { commandId: `${commandId}:link:${recordId}`, claimId: claim.id, evidenceItemId: itemId, role: "challenging", qualification: "retained by counter-search" }); challenging.push(itemId);
  }
  if (challenging.length !== contraryIds.length) {throw new ProjectStoreError("counter-search-incomplete", "counter-search did not create a challenging link for every contrary record");}
  const status: GapAssessment["status"] = contraryIds.length > 0 ? "revised" : "narrowed"; const qualification = contraryIds.length > 0 ? "counter-search retained contrary records in the scoped search" : "no-contrary-hits-in-scoped-search"; const counterId = recordId("counter-search"); const createdAt = isoNow(); transaction(handle.db, () => { handle.db.prepare("UPDATE gap_assessments SET status = ?, qualifications = ? WHERE id = ?").run(status, json([...gap.qualifications, qualification]), gap.id); handle.db.prepare("INSERT INTO counter_searches (id, gap_id, search_event_id, contrary_record_ids, challenging_evidence_item_ids, status, qualification, command_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(counterId, gap.id, event.id, json(contraryIds), json(challenging), status, qualification, commandId, createdAt); }); completeOperation(handle, commandId, counterId, "counter-search"); return { id: counterId, gap: gapRow(row(handle, "gap_assessments", gap.id)), searchEvent: event, snapshot, contraryCorpusRecordIds: contraryIds, challengingEvidenceItemIds: challenging };
}
function listCorpusSnapshotsInternal(handle: ProjectHandle, eventId: string): { id: string; searchEventId: string; corpusRecordIds: string[]; createdAt: string }[] { return (handle.db.prepare("SELECT * FROM corpus_snapshots WHERE search_event_id = ? ORDER BY created_at, id").all(eventId) as Array<Record<string, unknown>>).map((item) => ({ id: text(item, "id"), searchEventId: text(item, "search_event_id"), corpusRecordIds: parse(item.corpus_record_ids, []), createdAt: text(item, "created_at") })); }
function evidenceItemForSource(handle: ProjectHandle, sourceVersionId?: string): string | undefined { if (!sourceVersionId) {return undefined;} const found = handle.db.prepare("SELECT id FROM evidence_items WHERE source_version_id = ? ORDER BY created_at LIMIT 1").get(sourceVersionId) as { id?: string } | undefined; return found?.id; }
export function inspectGap(handle: ProjectHandle, capability: unknown, gapId: string): GapInspection { const gap = getGapAssessment(handle, capability, gapId); const snapshot = getCorpusSnapshot(handle, capability, gap.snapshotId); const contrary = (handle.db.prepare("SELECT DISTINCT c.* FROM corpus_records c JOIN counter_searches cs ON instr(cs.contrary_record_ids, c.id) > 0 WHERE cs.gap_id = ? ORDER BY c.created_at, c.id").all(gapId) as Array<Record<string, unknown>>).map((item) => ({ id: text(item, "id"), protocolVersionId: text(item, "protocol_version_id"), ...(typeof item.source_version_id === "string" ? { sourceVersionId: item.source_version_id } : {}), bibliographicIdentity: parse(item.bibliographic_identity, {}), origin: text(item, "origin") as CorpusRecord["origin"], createdAt: text(item, "created_at") })); const links = (handle.db.prepare("SELECT challenging_evidence_item_ids FROM counter_searches WHERE gap_id = ?").all(gapId) as Array<Record<string, unknown>>).flatMap((item) => parse<string[]>(item.challenging_evidence_item_ids, [])); return { gap, snapshot, contraryCorpusRecords: contrary, challengingEvidenceItemIds: [...new Set(links)] }; }
